"""Drawing a password.

Same source of randomness as the session tokens: the operating system's
cryptographic generator, never the ordinary one. A weak password generated by
mistake looks exactly like a strong one, so there is nothing to notice later.

Twenty characters from this alphabet is around 125 bits — far past anything worth
guessing at. There are no options, on purpose: a good fixed default is one less
thing to get wrong.
"""

from __future__ import annotations

import secrets
import string

LENGTH = 20
ALPHABET = string.ascii_letters + string.digits + "!#$%&*+-=?@^_~"


def new_password() -> str:
    drawn = [secrets.choice(ALPHABET) for _ in range(LENGTH)]
    return "".join(drawn)
